# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name=b'Balance, RUB')),
                ('inn', models.CharField(max_length=10, verbose_name=b'INN')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
